"""cultural_sites

Revision ID: 3dbd730a2590
Revises: 806ef4a2f16d
Create Date: 2025-12-16 21:26:52.446380

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '3dbd730a2590'
down_revision: Union[str, Sequence[str], None] = '806ef4a2f16d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cultural_sites',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('external_code', sa.String(length=64), nullable=True),
    sa.Column('name_tr', sa.String(length=255), nullable=False),
    sa.Column('name_en', sa.String(length=255), nullable=True),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('sub_category', sa.String(length=64), nullable=True),
    sa.Column('city', sa.String(length=64), nullable=True),
    sa.Column('district', sa.String(length=64), nullable=True),
    sa.Column('neighbourhood', sa.String(length=128), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('region_id', sa.String(length=32), nullable=True),
    sa.Column('summary_tr', sa.Text(), nullable=True),
    sa.Column('summary_en', sa.Text(), nullable=True),
    sa.Column('opening_hours', sa.String(length=64), nullable=True),
    sa.Column('ticket_required', sa.Boolean(), nullable=False),
    sa.Column('website', sa.Text(), nullable=True),
    sa.Column('main_image_url', sa.Text(), nullable=True),
    sa.Column('is_unesco', sa.Boolean(), nullable=False),
    sa.Column('protection_status', sa.String(length=64), nullable=True),
    sa.Column('source_name', sa.String(length=128), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('last_update', sa.Date(), nullable=True),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_code')
    )
  
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_cultural_sites_geom', table_name='cultural_sites', postgresql_using='gist')
    op.drop_table('cultural_sites')
    # ### end Alembic commands ###
